site_name: PandoraSim
nav:
    - Home: README.md
    - PandoraSim Conventions: conventions.ipynb
    - API:
      - Target: target.md
      - PandoraSim: pandorasim.md
      - NIRDA: irdetector.md
      - VISDA: visibledetector.md
      - PSF: psf.md
      - Optics: optics.md
      - Orbit: orbit.md
    - Notebooks:
      - WASP-69b Demo: WASP-69.ipynb
      - GJ 3470b Demo: GJ3470.ipynb
theme:
  name: "material"
  icon:
      logo: material/clipboard
repo_url: https://github.com/pandoramission/pandora-sim
plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      include_source: True
      ignore_h1_titles: False
  - mkdocstrings:
      watch:
        - src/pandorasim
